### ISSUE TITLE
question about php7

### ISSUE THREAD

**Issue by georgesuba** [lx-s/simple-image-share#1]
Hi, I love this simple tool, would like to ask about php7 update.. would it be somehow possible?

thanks.

**Comment by lx-s** [comment]
Hi!  (First of all: Thank you :))
Are you experiencing any specific problems with this tool and php 7.0?
I am running it on php7.0 and php7.1 without any problems myself

**Comment by georgesuba** [comment]
hi, well I think its complaining about fastcgi..i got this when I change php version to 7.0.19...

```
[Sat Sep 02 12:19:02.284951 2017] [fcgid:warn] [pid 6940] (104)Connection reset by peer: [client IP:43455] mod_fcgid: error reading data from FastCGI server
[Sat Sep 02 12:19:02.285081 2017] [core:error] [pid 6940] [client IP:43455] End of script output before headers: index.php
```

**Comment by lx-s** [comment]
Hm... Where you using mod_php before and switched to php-fpm for version 7?

(p.s. sorry for my slow answers, I am currently on vacation).

**Comment by georgesuba** [comment]
@lx-s its okay, I just came from  one too. well I did not check that.

**Comment by lx-s** [comment]
So, i'm back :)
Has it started working in the meantime or should we dig further?

**Comment by georgesuba** [comment]
@lx-s hi, well did not had time to check that out on another server.. I suspect the issue is perhaps how virtualmin sets the php versions on my debian server - upgraded from debian8 to debian9 so I have multiple php versions which could lead to problem when switching in virtualmin panel. I will install clean debian into virtualbox this weekend and test it with just php7 and will see. but if its working on yours it should works on mine. It could be apache settings as well. I will tell you more in Sunday :)

**Comment by lx-s** [comment]
Did you get around to fixing this issue? :)

**Comment by georgesuba** [comment]
Hi, sorry for very late update - yap everything's sorted!
